---
- block:
    - name: Instala o puppet-server no CentOS
      yum:
        name: puppetserver
        state: present
      when: ansible_distribution == "CentOS"

    - name: Instala o puppet-server no Ubuntu
      apt:
        name: puppetserver
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

  tags: server
